# Generated by Django 3.1.1 on 2022-08-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skill',
            },
        ),
        migrations.CreateModel(
            name='WhoAmI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('birth_day', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'WhoAmI',
                'verbose_name_plural': 'WhoAmIs',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
                ('impact', models.CharField(max_length=100)),
                ('take_away', models.CharField(max_length=100)),
                ('skill', models.ManyToManyField(blank=True, related_name='skill', to='main_api.Skill')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
