# Generated by Django 3.1.1 on 2022-08-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0002_auto_20220804_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='exp_years',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='learning_method',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
