# Generated by Django 3.1.1 on 2022-08-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0003_auto_20220804_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
