# Generated by Django 3.1.1 on 2022-08-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0005_auto_20220804_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=300)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('description', models.TextField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skill',
            },
        ),
    ]
