# Generated by Django 3.1.1 on 2022-08-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0006_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Position', 'verbose_name_plural': 'Position'},
        ),
        migrations.AlterField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='p_skill', to='main_api.Skill'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('description', models.TextField(max_length=100)),
                ('skill', models.ManyToManyField(blank=True, null=True, related_name='e_skill', to='main_api.Skill')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
