# Generated by Django 3.1.1 on 2022-08-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0008_auto_20220804_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='company_name',
        ),
        migrations.AddField(
            model_name='position',
            name='company_name',
            field=models.ManyToManyField(blank=True, null=True, related_name='p_org', to='main_api.Org'),
        ),
    ]
