# Generated by Django 3.1.1 on 2022-08-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0009_auto_20220804_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, related_name='ps_skill', to='main_api.Skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, related_name='pj_skill', to='main_api.Skill'),
        ),
    ]
