# Generated by Django 3.1.1 on 2022-08-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0010_auto_20220804_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='org',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='take_away',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='whoami',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
