# Generated by Django 3.1.1 on 2022-08-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0011_auto_20220804_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoami',
            name='skill_set',
            field=models.ManyToManyField(blank=True, related_name='skill', to='main_api.Skill'),
        ),
        migrations.AlterField(
            model_name='event',
            name='org',
            field=models.ManyToManyField(blank=True, related_name='org', to='main_api.Org'),
        ),
        migrations.AlterField(
            model_name='event',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='e_skill', to='main_api.Skill'),
        ),
        migrations.AlterField(
            model_name='position',
            name='company_name',
            field=models.ManyToManyField(blank=True, related_name='p_org', to='main_api.Org'),
        ),
        migrations.AlterField(
            model_name='position',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='ps_skill', to='main_api.Skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='pj_skill', to='main_api.Skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
