# Generated by Django 3.1.1 on 2022-08-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0012_auto_20220805_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='prj', to='main_api.Project'),
        ),
    ]
