# Generated by Django 3.1.1 on 2022-08-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0013_event_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoami',
            name='git_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='whoami',
            name='hobbies',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='whoami',
            name='ig_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='whoami',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='whoami',
            name='mail',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='whoami',
            name='orgs',
            field=models.ManyToManyField(blank=True, related_name='main_org', to='main_api.Org'),
        ),
    ]
