# Generated by Django 3.1.1 on 2022-08-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0015_auto_20220812_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoami',
            name='profile_img_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
