# Generated by Django 3.1.1 on 2022-08-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0018_auto_20220813_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='layout_position',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='org',
            name='layout_position',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='layout_position',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='layout_position',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='layout_position',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
