# Generated by Django 3.1.1 on 2022-08-15 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0020_skill_skill_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmt_time', models.DateTimeField(auto_now=True)),
                ('cmt_email', models.EmailField(max_length=500)),
                ('cmt_msg', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_time', models.DateTimeField(auto_now=True)),
                ('reply_msg', models.CharField(max_length=500)),
                ('reply_to_cmt', models.ForeignKey(blank=True, max_length=500, on_delete=django.db.models.deletion.CASCADE, related_name='reply_cmt', to='main_api.comment')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replys',
            },
        ),
    ]
