# Generated by Django 3.1.1 on 2022-08-15 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0021_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_to_cmt',
            field=models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_cmt', to='main_api.comment'),
        ),
    ]
