# Generated by Django 3.2.15 on 2022-08-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0022_auto_20220815_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVFile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=300)),
                ('pdf_file', models.FileField(blank=True, upload_to='pdfs')),
                ('img_file', models.FileField(blank=True, upload_to='imgs')),
            ],
            options={
                'verbose_name': 'CVFile',
                'verbose_name_plural': 'CVFiles',
            },
        ),
    ]
